### ISSUE TITLE
Potential issue with dependency on `f.length`

### ISSUE THREAD

**Issue by KeithHenry** [kutlugsahin/callback2promise#1]
This uses an explicit check on the arguments length for the function, but many native functions don't have explicit arguments:
```
// Native function with internal arguments
function nodeStyleFunc(){
    const param1 = arguments[0];
    const param2 = arguments[1];
    const callback = arguments[2];
    setTimeout(
        func(){ 
        callback(null, `done: ${param1}, ${param2}`) 
    }, 200);
}

// Params are not passed, because nodeStyleFunc.length === 0
const result = await c2p(nodeStyleFunc)('foo', 'bar');
```

The cause is https://github.com/kutlugsahin/callback2promise/blob/master/index.js line 5

Whether this is a problem will depend on what functions you attempt to call.

**Comment by kutlugsahin** [comment]
Thanks for pointing out, dependency to explicit arguments removed
